import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import Head from "next/head";

type User = {
  name: string;
  age: number;
  gender: "M" | "F";
};

interface SSRProp {
  user: User;
}

export const getServerSideProps: GetServerSideProps<SSRProp> = async () => {
  const user: User = {
    age: 20,
    gender: "M",
    name: "Prince Juguilon",
  };

  return {
    props: {
      user,
    },
  };
};

const Home: React.FC<InferGetServerSidePropsType<typeof getServerSideProps>> =
  ({ user }) => {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="w-full min-h-screen">{user.name}</main>

        <footer>Footer</footer>
      </>
    );
  };

export default Home;
